original_text = input('Enter some text: ')
crypted_text = original_text.replace('a','4')
crypted_text = crypted_text.replace('b','8')
crypted_text = crypted_text.replace('e','3')
crypted_text = crypted_text.replace('l','1')
crypted_text = crypted_text.replace('o','0')
crypted_text = crypted_text.replace('s','5')
crypted_text = crypted_text.replace('t','7')
print(original_text)
